## Long Short-Term Memory 
for more detials check the pdf of this session: https://github.com/sumaia-a-k/NLP-2026/wiki/LSTM

In [101]:
def read_file(filePath):
    with open(filePath) as f:
        str_text = f.read()

    return str_text

In [102]:
read_file('moby_dick_four_chapters.txt')

'Call me Ishmael.  Some years ago--never mind how long\nprecisely--having little or no money in my purse, and nothing\nparticular to interest me on shore, I thought I would sail about a\nlittle and see the watery part of the world.  It is a way I have of\ndriving off the spleen and regulating the circulation.  Whenever I\nfind myself growing grim about the mouth; whenever it is a damp,\ndrizzly November in my soul; whenever I find myself involuntarily\npausing before coffin warehouses, and bringing up the rear of every\nfuneral I meet; and especially whenever my hypos get such an upper\nhand of me, that it requires a strong moral principle to prevent me\nfrom deliberately stepping into the street, and methodically knocking\npeople\'s hats off--then, I account it high time to get to sea as soon\nas I can.  This is my substitute for pistol and ball.  With a\nphilosophical flourish Cato throws himself upon his sword; I quietly\ntake to the ship.  There is nothing surprising in this.  If t

In [103]:
# tokenize and clean the text 
import spacy

In [104]:
nlp = spacy.load("en_core_web_sm" , disable = ['parser', 'tagger' , 'net'])

In [105]:
nlp.max_length = 1198623 # sometimes we need to increase it just in case

In [106]:
def separate_punc(doc_text):
    return [token.text.lower() for token in nlp(doc_text) if token.text not in '\n\n \n\n\n!"-#$%&()--.*+,-/:;<=>?@[\\]^_`{|}~\t\n ']

In [ ]:
d = read_file('moby_dick_four_chapters.txt')
tokens = separate_punc(d)

In [108]:
len(tokens)

11338

In [109]:
# we need to create sequence of tokens 
# we are going to pass first 49 words of the sentence and let our network predict the next word 
# 49 word ==> network predict #50
train_len = 49+1 
text_sequences = []

for i in range(train_len, len(tokens)):
    
    # Grab train_len# amount of characters
    seq = tokens[i-train_len:i]
    
    # Add to list of sequences
    text_sequences.append(seq)

In [110]:
type(text_sequences)

list

In [111]:
text_sequences[0]

['call',
 'me',
 'ishmael',
 'some',
 'years',
 'ago',
 'never',
 'mind',
 'how',
 'long',
 'precisely',
 'having',
 'little',
 'or',
 'no',
 'money',
 'in',
 'my',
 'purse',
 'and',
 'nothing',
 'particular',
 'to',
 'interest',
 'me',
 'on',
 'shore',
 'i',
 'thought',
 'i',
 'would',
 'sail',
 'about',
 'a',
 'little',
 'and',
 'see',
 'the',
 'watery',
 'part',
 'of',
 'the',
 'world',
 'it',
 'is',
 'a',
 'way',
 'i',
 'have',
 'of']

In [112]:
' '.join(text_sequences[0])

'call me ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to interest me on shore i thought i would sail about a little and see the watery part of the world it is a way i have of'

In [113]:
' '.join(text_sequences[1])

'me ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to interest me on shore i thought i would sail about a little and see the watery part of the world it is a way i have of driving'

---------------

In [114]:
# keras tokenization to format this in numeric system that keras understands
from tensorflow.keras.preprocessing.text import Tokenizer

In [115]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(text_sequences)
sequences = tokenizer.texts_to_sequences(text_sequences)

In [116]:
sequences[0]

[956,
 14,
 262,
 50,
 261,
 408,
 87,
 219,
 129,
 120,
 954,
 260,
 52,
 43,
 38,
 314,
 7,
 23,
 546,
 3,
 150,
 259,
 6,
 2713,
 14,
 25,
 2711,
 5,
 60,
 5,
 59,
 406,
 37,
 2,
 52,
 3,
 101,
 1,
 2710,
 176,
 4,
 1,
 175,
 8,
 20,
 2,
 109,
 5,
 48,
 4]

In [117]:
sequences[1]

[14,
 262,
 50,
 261,
 408,
 87,
 219,
 129,
 120,
 954,
 260,
 52,
 43,
 38,
 314,
 7,
 23,
 546,
 3,
 150,
 259,
 6,
 2713,
 14,
 25,
 2711,
 5,
 60,
 5,
 59,
 406,
 37,
 2,
 52,
 3,
 101,
 1,
 2710,
 176,
 4,
 1,
 175,
 8,
 20,
 2,
 109,
 5,
 48,
 4,
 957]

In [118]:
tokenizer.index_word

{1: 'the',
 2: 'a',
 3: 'and',
 4: 'of',
 5: 'i',
 6: 'to',
 7: 'in',
 8: 'it',
 9: 'that',
 10: 'he',
 11: 'his',
 12: 'was',
 13: 'but',
 14: 'me',
 15: 'with',
 16: 'as',
 17: 'at',
 18: 'this',
 19: 'you',
 20: 'is',
 21: 'all',
 22: 'for',
 23: 'my',
 24: 'be',
 25: 'on',
 26: "'s",
 27: 'not',
 28: 'from',
 29: 'there',
 30: 'one',
 31: 'up',
 32: 'what',
 33: 'him',
 34: 'so',
 35: 'bed',
 36: 'now',
 37: 'about',
 38: 'no',
 39: 'into',
 40: 'by',
 41: 'were',
 42: 'out',
 43: 'or',
 44: 'harpooneer',
 45: 'had',
 46: 'then',
 47: 'an',
 48: 'have',
 49: 'upon',
 50: 'some',
 51: 'old',
 52: 'little',
 53: 'like',
 54: 'if',
 55: 'they',
 56: 'do',
 57: 'over',
 58: 'landlord',
 59: 'would',
 60: 'thought',
 61: 'room',
 62: 'when',
 63: 'could',
 64: "n't",
 65: 'night',
 66: 'here',
 67: 'head',
 68: 'such',
 69: 'which',
 70: 'man',
 71: 'did',
 72: 'sea',
 73: 'time',
 74: 'other',
 75: 'very',
 76: 'go',
 77: 'these',
 78: 'more',
 79: 'though',
 80: 'first',
 81: 'sort',


In [119]:
tokenizer.word_counts

OrderedDict([('call', 51),
             ('me', 4727),
             ('ishmael', 253),
             ('some', 1454),
             ('years', 255),
             ('ago', 156),
             ('never', 857),
             ('mind', 308),
             ('how', 601),
             ('long', 698),
             ('precisely', 61),
             ('having', 262),
             ('little', 1448),
             ('or', 1814),
             ('no', 1915),
             ('money', 216),
             ('in', 10831),
             ('my', 3418),
             ('purse', 119),
             ('and', 18481),
             ('nothing', 521),
             ('particular', 272),
             ('to', 12473),
             ('interest', 24),
             ('on', 3276),
             ('shore', 27),
             ('i', 13706),
             ('thought', 1279),
             ('would', 1331),
             ('sail', 182),
             ('about', 1933),
             ('a', 19930),
             ('see', 787),
             ('the', 29819),
             ('water

In [120]:
vocabulary_size = len(tokenizer.word_counts)
vocabulary_size

2718

In [121]:
# convert to numpy 
import numpy as np
sequences = np.array(sequences)
sequences

array([[ 956,   14,  262, ...,    5,   48,    4],
       [  14,  262,   50, ...,   48,    4,  957],
       [ 262,   50,  261, ...,    4,  957,   94],
       ...,
       [ 351, 2708,    1, ...,  263,   53,    2],
       [2708,    1,   67, ...,   53,    2, 2718],
       [   1,   67,    4, ...,    2, 2718,   26]])

------

In [122]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,LSTM,Embedding

In [123]:
from tensorflow.keras.utils import to_categorical

In [124]:
sequences

array([[ 956,   14,  262, ...,    5,   48,    4],
       [  14,  262,   50, ...,   48,    4,  957],
       [ 262,   50,  261, ...,    4,  957,   94],
       ...,
       [ 351, 2708,    1, ...,  263,   53,    2],
       [2708,    1,   67, ...,   53,    2, 2718],
       [   1,   67,    4, ...,    2, 2718,   26]])

In [125]:
# First 49 words
sequences[:,:-1]

array([[ 956,   14,  262, ...,  109,    5,   48],
       [  14,  262,   50, ...,    5,   48,    4],
       [ 262,   50,  261, ...,   48,    4,  957],
       ...,
       [ 351, 2708,    1, ...,   11,  263,   53],
       [2708,    1,   67, ...,  263,   53,    2],
       [   1,   67,    4, ...,   53,    2, 2718]])

In [126]:
sequences[:,-1]

array([   4,  957,   94, ...,    2, 2718,   26])

In [127]:
X = sequences[:,:-1]
y = sequences[:,-1]

In [128]:
seq_len = X.shape[1]
print(seq_len)

49


In [129]:
# change Y to catgegory 
y = to_categorical(y, num_classes=vocabulary_size+1) # +1 for the padding zeros

In [130]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,LSTM,Embedding

In [131]:
def create_model(vocabulary_size, sl):
    model = Sequential()
    # input dim = vocabulary_size , output_dim = sequnce length (sl)
    model.add(Embedding(vocabulary_size, sl)) # has to be the first layer in the model
    model.add(LSTM(150, return_sequences=True)) 
    model.add(LSTM(150))
    model.add(Dense(150, activation='relu'))

    model.add(Dense(vocabulary_size, activation='softmax'))
    
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    
    return model

In [132]:
model = create_model(vocabulary_size+1, seq_len)

In [133]:
from pickle import dump,load 
model.fit(X, y, batch_size=128, epochs=10,verbose=1)

Epoch 1/10
89/89 ━━━━━━━━━━━━━━━━━━━━ 26s 227ms/step - accuracy: 0.0436 - loss: 6.8478
Epoch 2/10
89/89 ━━━━━━━━━━━━━━━━━━━━ 18s 205ms/step - accuracy: 0.0528 - loss: 6.3443
Epoch 3/10
89/89 ━━━━━━━━━━━━━━━━━━━━ 19s 215ms/step - accuracy: 0.0528 - loss: 6.2112
Epoch 4/10
89/89 ━━━━━━━━━━━━━━━━━━━━ 19s 208ms/step - accuracy: 0.0577 - loss: 6.0817
Epoch 5/10
89/89 ━━━━━━━━━━━━━━━━━━━━ 18s 200ms/step - accuracy: 0.0660 - loss: 5.9235
Epoch 6/10
89/89 ━━━━━━━━━━━━━━━━━━━━ 18s 202ms/step - accuracy: 0.0684 - loss: 5.8127
Epoch 7/10
89/89 ━━━━━━━━━━━━━━━━━━━━ 17s 192ms/step - accuracy: 0.0694 - loss: 5.7103
Epoch 8/10
89/89 ━━━━━━━━━━━━━━━━━━━━ 17s 191ms/step - accuracy: 0.0707 - loss: 5.6286
Epoch 9/10
89/89 ━━━━━━━━━━━━━━━━━━━━ 18s 199ms/step - accuracy: 0.0724 - loss: 5.5565
Epoch 10/10
89/89 ━━━━━━━━━━━━━━━━━━━━ 19s 211ms/step - accuracy: 0.0718 - loss: 5.4950


In [134]:
model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)              │ (None, 49, 49)              │         133,231 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_10 (LSTM)                       │ (None, 49, 150)             │         120,000 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_11 (LSTM)                       │ (None, 150)                 │         180,600 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_10 (Dense)                     │ (None, 150)                 │          22,650 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_11 (Dense)                     │ (None, 2719)                │         410,569 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 2,601,152 (9.92 MB)

 Trainable params: 867,050 (3.31 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 1,734,102 (6.62 MB)

In [135]:
# save the model to file
model.save('myGenerateWord.keras')
# save the tokenizer
dump(tokenizer, open('myGenerateWord', 'wb'))

------

In [136]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [137]:
def generate_text(model, tokenizer, seq_len, seed_text, num_gen_words):
    '''
    INPUTS:
    model : model that was trained on text data
    tokenizer : tokenizer that was fit on text data
    seq_len : length of training sequence
    seed_text : raw string text to serve as the seed
    num_gen_words : number of words to be generated by model
    '''
    
    # Final Output
    output_text = []
    
    # Intial Seed Sequence
    input_text = seed_text
    
    # Create num_gen_words
    for i in range(num_gen_words):
        
        # Take the input text string and encode it to a sequence
        encoded_text = tokenizer.texts_to_sequences([input_text])[0]
        
        # Pad sequences to our trained rate 49
        pad_encoded = pad_sequences([encoded_text], maxlen=seq_len, truncating='pre')
        
        # Predict raw probabilities for all words in vocabulary
        raw_predictions = model.predict(pad_encoded, verbose=0)[0]

        # Extract index of the highest probability word using argmax
        pred_word_ind = np.argmax(raw_predictions)

        # Grab word
        pred_word = tokenizer.index_word[pred_word_ind] 
        
        # Update the sequence of input text (shifting one over with the new word)
        input_text += ' ' + pred_word
        
        output_text.append(pred_word)
        
    # Make it look like a sentence.
    return ' '.join(output_text)

In [140]:
seed_text = "Call me drawn toward the fathomless ocean whenever the damp November of my soul grows cold. There sails the grand phantom of the whale through stormy waters, a majestic creature pursued by a mad captain across the rolling tides of the vast Pacific, seeking vengeance upon the great white monster" 

In [141]:
generate_text(model,tokenizer,seq_len,seed_text=seed_text,num_gen_words=10)

'and a room and the room and the room and'