In [1]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer, HashingVectorizer
from nltk import bigrams
import nltk

feedback = [
    "The food was great and the service was fast.",
    "The service was slow but the food was delicious.",
    "Great food and amazing service."
]


### Using BiGram:

In [15]:
cv = CountVectorizer(ngram_range=(2, 2), stop_words='english')
bigram_counts = cv.fit_transform(feedback)

print(cv.vocabulary_,"\n")
print(bigram_counts.toarray())

{'food great': 3, 'great service': 5, 'service fast': 6, 'service slow': 7, 'slow food': 8, 'food delicious': 2, 'great food': 4, 'food amazing': 1, 'amazing service': 0} 

[[0 0 0 1 0 1 1 0 0]
 [0 0 1 0 0 0 0 1 1]
 [1 1 0 0 1 0 0 0 0]]


### Using Co-Occurrence Matrix:

In [17]:
tokens = " ".join(feedback).lower().split()
vocab = sorted(list(set(tokens)))
word_to_id = {word: i for i, word in enumerate(vocab)}

# Building the matrix
co_matrix = np.zeros((len(vocab), len(vocab)))
for w1, w2 in bigrams(tokens):
    co_matrix[word_to_id[w2]][word_to_id[w1]] += 1

df_co = pd.DataFrame(co_matrix, index=vocab, columns=vocab)

print(df_co,"\n")
print (df_co.shape)

            amazing  and  but  delicious.  fast.  food  great  service  \
amazing         0.0  1.0  0.0         0.0    0.0   0.0    0.0      0.0   
and             0.0  0.0  0.0         0.0    0.0   1.0    1.0      0.0   
but             0.0  0.0  0.0         0.0    0.0   0.0    0.0      0.0   
delicious.      0.0  0.0  0.0         0.0    0.0   0.0    0.0      0.0   
fast.           0.0  0.0  0.0         0.0    0.0   0.0    0.0      0.0   
food            0.0  0.0  0.0         0.0    0.0   0.0    1.0      0.0   
great           0.0  0.0  0.0         1.0    0.0   0.0    0.0      0.0   
service         0.0  0.0  0.0         0.0    0.0   0.0    0.0      0.0   
service.        1.0  0.0  0.0         0.0    0.0   0.0    0.0      0.0   
slow            0.0  0.0  0.0         0.0    0.0   0.0    0.0      0.0   
the             0.0  1.0  1.0         0.0    1.0   0.0    0.0      0.0   
was             0.0  0.0  0.0         0.0    0.0   2.0    0.0      2.0   

            service.  slow  the  was 

### Using Hash-Vectorizer

In [18]:
hv = HashingVectorizer(n_features=5)
hashed_output = hv.transform(feedback)

print(hashed_output.toarray(),"\n")
print (hashed_output.shape)

[[-0.30151134  0.60302269 -0.30151134 -0.60302269  0.30151134]
 [ 0.22941573  0.45883147  0.22941573 -0.6882472   0.45883147]
 [-1.          0.          0.          0.          0.        ]] 

(3, 5)
